apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      nodeSelector:
        elastic: eck
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  kibanaRef:
    name: quickstart