apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: ${namespace}
spec:
  version: 8.6.2
  nodeSets:
  %{~ for k, v in nodeset_config ~}
  - name: ${k}
    count: ${v.count}
    config:
      node.roles: [${join(", ", v.roles)}]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: elastic
                      operator: In
                      values:
                        - eck
                topologyKey: zone
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${v.storage}
        storageClassName: ${v.storageClassName}
  %{~ endfor ~}
