apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      nodeSelector:
        elastic: eck
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.basePath: /kibana
    server.rewriteBasePath: false
    server.publicBaseUrl: ${external_domain}
    server.name: "kibana"
    csp.strict: false
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-quickstart-es-http.default.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-quickstart-agent-http.default.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
      - name: apm
        version: latest
    xpack.fleet.agentPolicies:
      # - name: Fleet Server on ECK policy
      #   id: eck-fleet-server
      #   is_default_fleet_server: true
      #   namespace: fleet_agent
      #   monitoring_enabled:
      #     - logs
      #     - metrics
      #   unenroll_timeout: 900
      #   package_policies:
      #   - name: fleet_server-1
      #     id: fleet_server-1
      #     package:
      #       name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: eck_agent
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
        # - name: system-1
        #   package:
        #     name: system
        %{~ for k, v in agent_config_container_logs ~}
        - id: kubernetes-${k}
          name: kubernetes-${k}
          namespace: ${v.data_stream_namespace}
          package:
            name: kubernetes
        %{~ endfor ~}
        - id: apm-1
          name: apm-1
          namespace: apm
          package:
            name: apm
          inputs:
          - type: apm
            enabled: true
            vars:
            - name: host
              value: 0.0.0.0:8200    
    #xpack:
    #  security:
    #    authc:
    #      providers:
    #        saml:
    #          kibana-realm:
    #            order: 0
    #            realm: kibana-realm
    #            description: "Log in with Azure AD"